reformat and enforce

diff --git a/.github/workflows/python_ci.yml b/.github/workflows/python_ci.yml
--- a/.github/workflows/python_ci.yml
+++ b/.github/workflows/python_ci.yml
@@ -22,14 +22,18 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install pytest  # Install pytest or your test runner
-        pip install pylint  # Install pylint for code quality checks
-        pip install -r requirements.txt  # Install other project dependencies
+        pip install -r requirements.txt  # Install project dependencies
 
     - name: Run tests
-      run: pytest tests/test_app.py  # Run the tests
+      run: pytest /test/test_app.py  # Run the tests
 
-    - name: Lint with pylint
+    - name: Run black (reformat code)
+      run: black .  # Automatically reformat the code according to black's standards
+
+    - name: Commit and push if changes
       run: |
-        # Run pylint on all python files
-        pylint $(find . -type f -name "*.py")
+        git config --global user.email "actions@github.com"
+        git config --global user.name "GitHub Actions"
+        git add -A
+        git commit -m "Apply black formatting" -a || true  # This will not fail if there's nothing to commit
+        git push
